blueprint:
  name: Low battery level detection & notification for all battery sensors
  description: Regularly test all sensors with 'battery' device-class for crossing
    a certain battery level threshold and if so execute an action.

    Forked from https://github.com/vgelot/ha-blueprints/blob/main/blueprints/automation/low_battery_detection_and_notification/low_battery_detection_and_notification.yaml
    Changed sensors to be kept as an array instead of joining as a string.
  domain: automation
  input:
    threshold:
      name: Battery warning level threshold
      description: Battery sensors below threshold are assumed to be low-battery (as
        well as binary battery sensors with value 'on').
      default: 20
      selector:
        number:
          min: 5.0
          max: 100.0
          unit_of_measurement: '%'
          mode: slider
          step: 5.0
    time:
      name: Time to test on
      description: Test is run at configured time
      default: '10:00:00'
      selector:
        time: {}
    days:
      name: (Required) Days
      description: Days of the week when the automation is active.
      selector:
        select:
          options:
          - Monday
          - Tuesday
          - Wednesday
          - Thursday
          - Friday
          - Saturday
          - Sunday
          mode: list
          multiple: true
          custom_value: false
          sort: false
    exclude:
      name: Excluded Sensors
      description: Battery sensors (e.g. smartphone) to exclude from detection. Only
        entities are supported, devices must be expanded!
      default:
        entity_id: []
      selector:
        target:
          entity:
          - device_class:
            - battery
    actions:
      name: Actions
      description: Notifications or similar to be run. The filtered sensors are on the "sensors" array variable.
      selector:
        action: {}
  source_url: https://github.com/ShadowBelmolve/home-assistant-blueprints/blob/main/automations/low-battery/low_battery_detection_and_notification.yaml
variables:
  days: !input days
  threshold: !input threshold
  exclude: !input exclude
  sensors: >
    {% set result = namespace(sensors=[]) %}
    {% for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') %}
      {% if 0 <= state.state | int(-1) < threshold | int and not state.entity_id in exclude.entity_id %}
        {% set result.sensors = result.sensors + [state.name ~ ' (' ~ state.state ~ ' %)'] %}
      {% endif %}
    {% endfor %}
    {% for state in states.binary_sensor | selectattr('attributes.device_class', '==', 'battery') | selectattr('state', '==', 'on') %}
      {% if not state.entity_id in exclude.entity_id %}
        {% set result.sensors = result.sensors + [state.name] %}
      {% endif %}
    {% endfor %}
    {{ result.sensors }}
trigger:
  - platform: time
    at: !input time
condition:
  - condition: template
    value_template: '{{ sensors | count > 0 and now().strftime(''%A'') in days }}'
action:
  - choose: []
    default: !input actions
mode: single